[package]
name = "imagecrusher"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "imagecrusher"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
image = "0.24.6"